# Generated by Django 5.1 on 2026-09-25 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Código QR')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('responsable_familia', models.CharField(max_length=150, verbose_name='Responsable de familia')),
                ('num_habitantes', models.PositiveIntegerField(default=0, verbose_name='Número de habitantes')),
                ('zona', models.CharField(blank=True, max_length=50, verbose_name='Zona')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='Referencia de ubicación')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Imagen QR')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viviendas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ViviendaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('responsable_familia', models.CharField(max_length=150)),
                ('num_habitantes', models.PositiveIntegerField(default=0)),
                ('zona', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tipo_operacion', models.CharField(choices=[('INSERT', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE_LOGICO', 'Eliminación lógica')], max_length=20)),
                ('usuario_cambio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_viviendas', to=settings.AUTH_USER_MODEL)),
                ('vivienda_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='viviendas.vivienda')),
            ],
            options={
                'verbose_name': 'Historial de Vivienda',
                'verbose_name_plural': 'Historial de Viviendas',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
