# Generated by Django 5.1 on 2026-09-25 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viviendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateTimeField(auto_now_add=True)),
                ('num_depositos', models.PositiveIntegerField(default=0, verbose_name='Depósitos inspeccionados')),
                ('depositos_positivos', models.PositiveIntegerField(default=0, verbose_name='Depósitos positivos con larvas')),
                ('presencia_larvas', models.BooleanField(default=False, verbose_name='¿Presencia de larvas?')),
                ('criaderos_potenciales', models.BooleanField(default=False, verbose_name='¿Criaderos potenciales?')),
                ('aplico_larvicida', models.BooleanField(default=False, verbose_name='Aplicó larvicida')),
                ('elimino_criaderos', models.BooleanField(default=False, verbose_name='Eliminó criaderos')),
                ('programo_fumigacion', models.BooleanField(default=False, verbose_name='Programó fumigación')),
                ('educo_residente', models.BooleanField(default=False, verbose_name='Educación al residente')),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10, verbose_name='Nivel de riesgo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsable')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='viviendas.vivienda', verbose_name='Vivienda')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-fecha_inspeccion'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vivienda_codigo', models.CharField(max_length=100)),
                ('presencia_larvas', models.BooleanField(default=False)),
                ('criaderos_potenciales', models.BooleanField(default=False)),
                ('nivel_riesgo', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tipo_operacion', models.CharField(choices=[('INSERT', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE_LOGICO', 'Eliminación lógica')], max_length=20)),
                ('inspeccion_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inspecciones.inspeccion')),
                ('usuario_cambio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_inspecciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Inspección',
                'verbose_name_plural': 'Historial de Inspecciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
